export const MENU = [
    {
        id: 1,
        image: '/images/menu/item1.png',
        title: "Sandwich",
        detail: "bread with meat and vegetables",
        price: "12",
        rating: 4.8,
    },
    {
        id: 2,
        image: '/images/menu/item2.png',
        title: "Hot Milk",
        detail: "Hot Milk with less sugar",
        price: "12",
        rating: 4.8,
    },
    {
        id: 3,
        image: '/images/menu/item3.png',
        title: "Coffe Ice Cream",
        detail: "Coffe with ice cream vanilla",
        price: "12",
        rating: 4.8,
    },
    {
        id: 4,
        image: '/images/menu/item4.png',
        title: "Cappucino",
        detail: "Hot Cappucino",
        price: "12",
        rating: 4.8,
    },
    {
        id: 5,
        image: '/images/menu/item5.png',
        title: "Moccacinno",
        detail: "Hot Moccacino",
        price: "12",
        rating: 4.8,
    },
    {
        id: 6,
        image: '/images/menu/item6.png',
        title: "Waffle Ice Crem",
        detail: "Waffle with ice cream vanilla",
        price: "12",
        rating: 4.8,
    },
    {
        id: 7,
        image: '/images/popular/vanilla-latte.png',
        title: "Vanilla Latte",
        detail: "Vanilla Latte with less sugar",
        price: "12",
        rating: 4.8,
    },
    {
        id: 8,
        image: '/images/popular/espresso.png',
        title: "Espresso",
        detail: "Espresso with less sugar",
        price: "12",
        rating: 4.8,
    },
    {
        id: 9,
        image: '/images/popular/hazelnut-latte.png',
        title: "Hazelnut Latte",
        detail: "Hazelnut Latte with less sugar",
        price: "12",
        rating: 4.8,
    }
]

